import type { TransferLogEntry } from "./types";

// Mock data layer mirroring the shape of the ported /live-transfer-logs
// feed (public registry transfer records), so this can be swapped for a
// live fetch without touching call sites.
const TRANSFER_LOGS: TransferLogEntry[] = [
  {
    id: "TL-01",
    transferDate: "08/13/2026",
    ipv4Range: "104.28.0.0/22",
    recipientOrg: "Arkview Hosting Inc.",
    sourceOrg: "Meridian Networks LLC",
    registrationDate: "03/11/2009",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-02",
    transferDate: "08/12/2026",
    ipv4Range: "192.168.14.0/24",
    recipientOrg: "Northline Data Partners",
    sourceOrg: "Cobalt Systems Group",
    registrationDate: "07/02/2011",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-03",
    transferDate: "08/11/2026",
    ipv4Range: "82.14.66.0/21",
    recipientOrg: "Bluewave Broadband Services, LLC",
    sourceOrg: "Vantage IX Holdings",
    registrationDate: "01/19/2007",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-04",
    transferDate: "08/10/2026",
    ipv4Range: "45.62.0.0/20",
    recipientOrg: "Fenwick Cloud Partners",
    sourceOrg: "Silverline Colo LLC",
    registrationDate: "09/28/2013",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-05",
    transferDate: "08/09/2026",
    ipv4Range: "185.44.0.0/23",
    recipientOrg: "Northline Data Partners",
    sourceOrg: "Bastion Peering Ltd.",
    registrationDate: "05/14/2010",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-06",
    transferDate: "08/08/2026",
    ipv4Range: "103.22.0.0/22",
    recipientOrg: "Wavelength Networks Ltd.",
    sourceOrg: "Quaystone Networks",
    registrationDate: "11/03/2012",
    transferType: "MERGER_ACQUISITION",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-07",
    transferDate: "08/07/2026",
    ipv4Range: "200.58.0.0/21",
    recipientOrg: "Arkview Hosting Inc.",
    sourceOrg: "Redline Systems Inc.",
    registrationDate: "02/25/2008",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-08",
    transferDate: "08/06/2026",
    ipv4Range: "165.90.0.0/24",
    recipientOrg: "Cedarpoint Communications",
    sourceOrg: "Ironclad Data Systems",
    registrationDate: "06/30/2015",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-09",
    transferDate: "08/05/2026",
    ipv4Range: "41.75.0.0/19",
    recipientOrg: "Halcyon Broadband LLC",
    sourceOrg: "Solace Cloud Group",
    registrationDate: "04/17/2014",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-10",
    transferDate: "08/04/2026",
    ipv4Range: "179.32.0.0/20",
    recipientOrg: "Pinehurst Connectivity",
    sourceOrg: "Redline Systems Inc.",
    registrationDate: "08/09/2009",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-11",
    transferDate: "08/03/2026",
    ipv4Range: "154.16.0.0/18",
    recipientOrg: "Solace Cloud Group",
    sourceOrg: "Wavelength Networks Ltd.",
    registrationDate: "12/01/2016",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-12",
    transferDate: "08/02/2026",
    ipv4Range: "77.104.0.0/21",
    recipientOrg: "Bastion Peering Ltd.",
    sourceOrg: "Meridian Networks LLC",
    registrationDate: "10/22/2006",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-13",
    transferDate: "07/31/2026",
    ipv4Range: "116.90.0.0/22",
    recipientOrg: "Ironclad Data Systems",
    sourceOrg: "Cedarpoint Communications",
    registrationDate: "03/05/2018",
    transferType: "MERGER_ACQUISITION",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-14",
    transferDate: "07/29/2026",
    ipv4Range: "168.121.0.0/16",
    recipientOrg: "Quaystone Networks",
    sourceOrg: "Halcyon Broadband LLC",
    registrationDate: "07/13/2005",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
  {
    id: "TL-15",
    transferDate: "07/26/2026",
    ipv4Range: "196.44.0.0/21",
    recipientOrg: "Cobalt Systems Group",
    sourceOrg: "Pinehurst Connectivity",
    registrationDate: "09/09/2011",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "RIPE",
    recipientRir: "RIPE",
  },
  {
    id: "TL-16",
    transferDate: "07/22/2026",
    ipv4Range: "58.96.0.0/17",
    recipientOrg: "Vantage IX Holdings",
    sourceOrg: "Northline Data Partners",
    registrationDate: "02/17/2013",
    transferType: "RESOURCE_TRANSFER",
    sourceRir: "ARIN",
    recipientRir: "ARIN",
  },
];

export async function getTransferLogs(): Promise<TransferLogEntry[]> {
  return TRANSFER_LOGS;
}
